tags:
  - name: Products
    description: مدیریت محصولات

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        final_price:
          type: integer
        stock_status:
          type: string
        is_featured:
          type: boolean

paths:
  /products:
    get:
      tags: [Products]
      summary: لیست محصولات
      responses:
        200:
          description: Success

    post:
      tags: [Products]
      summary: ایجاد محصول
      security:
        - bearerAuth: []
      responses:
        201:
          description: Created

  /products/{slug}:
    get:
      tags: [Products]
      summary: دریافت محصول
      responses:
        200:
          description: Success

  /products/{id}:
    put:
      tags: [Products]
      summary: ویرایش محصول
      security:
        - bearerAuth: []
      responses:
        200:
          description: Updated

    delete:
      tags: [Products]
      summary: حذف محصول
      security:
        - bearerAuth: []
      responses:
        200:
          description: Deleted

  /products/stock:
    patch:
      tags: [Products]
      summary: بروزرسانی موجودی
      security:
        - bearerAuth: []
      responses:
        200:
          description: Updated
